name: CI

on:
  push:
    paths:
      - '**.gradle'
      - '**.properties'
      - '**/src/**'
      - '.github/workflows/**'
    branches: [ master ]
    tags-ignore:
      - '*.*'
  pull_request:
    paths:
      - '**.gradle'
      - '**.properties'
      - '**/src/**'
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  build:
    name: Build for JDK ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 16 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build
        run: ./gradlew clean build
      - name: Run tests
        run: ./gradlew test
